### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by yashchoubey** [google-research/language#24]
Command:

- sudo pip3 install bert-tensorflow natural-questions

Version:

- python: 3.7
- tensorflow: 2.0
- pip: 19.2

Logs:

Collecting wsgiref (from natural-questions)
  Downloading https://files.pythonhosted.org/packages/41/9e/309259ce8dff8c596e8c26df86dbc4e848b9249fd36797fd60be456f03fc/wsgiref-0.1.2.zip
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-y1d6cb8r/wsgiref/setup.py'"'"'; __file__='"'"'/tmp/pip-install-y1d6cb8r/wsgiref/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-y1d6cb8r/wsgiref/
    Complete output (8 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-y1d6cb8r/wsgiref/setup.py", line 5, in <module>
        import ez_setup
      File "/tmp/pip-install-y1d6cb8r/wsgiref/ez_setup/__init__.py", line 170
        print "Setuptools version",version,"or greater has been installed."
                                 ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Setuptools version",version,"or greater has been installed.")?
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by kokoinyannn** [comment]
try --no-dependencies flag

ref: https://github.com/google-research/language/issues/5
