### ISSUE TITLE
BERT Baseline NQ pip install issue

### ISSUE THREAD

**Issue by zzj0402** [google-research/language#43]
pip install seems installing the file to python2 packages.  
`pip3 install bert-tensorflow natural-questions` outputs:
```python
Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-52v2v26x/wsgiref/setup.py", line 5, in <module>
        import ez_setup
      File "/tmp/pip-build-52v2v26x/wsgiref/ez_setup/__init__.py", line 170
        print "Setuptools version",version,"or greater has been installed."
                                 ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Setuptools version",version,"or greater has been installed.")?
```

**Comment by igeti** [comment]
try
https://github.com/google-research/language/issues/24#issuecomment-555802597
