### ISSUE TITLE
Code example for pre-trained REALM models?

### ISSUE THREAD

**Issue by youssefavx** [google-research/language#67]
Hey! I'd like to try out the pre-trained REALM models (meaning ask a question and get an answer), but was wondering if there were any code examples we could try to use it? I haven't found any in the read me.

**Comment by kentonl** [comment]
We just released fine-tuned models here: https://github.com/google-research/language/tree/master/language/realm#pre-trained-model-checkpoints. I suggest trying out the Natural Questions-based model. If you set `--model_dir=gs://realm-data/orqa_nq_model_from_realm` in the ORQA demo (https://github.com/google-research/language/tree/master/language/orqa#running-the-demo), you can demo with your own questions.

**Comment by youssefavx** [comment]
Thanks so much! I gave this a try and got an error when running:

`pip install -r language/orqa/requirements.txt`
I got: 

`ERROR: scann-1.0.0-cp37-cp37m-linux_x86_64.whl is not a supported wheel on this platform.`

Then I installed everything except for that file manually, and when running this:

```
python -m language.orqa.predict.orqa_demo \
  --model_dir=gs://realm-data/orqa_nq_model_from_realm \
  --port=8080
```
I got this error:

```
Traceback (most recent call last):
  File "/Users/ya/Documents/realm/language/language/orqa/ops/__init__.py", line 20, in <module>
    orqa_ops
NameError: name 'orqa_ops' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ya/opt/anaconda3/envs/orqa/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/ya/opt/anaconda3/envs/orqa/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/ya/Documents/realm/language/language/orqa/predict/orqa_demo.py", line 22, in <module>
    from language.orqa.models import orqa_model
  File "/Users/ya/Documents/realm/language/language/orqa/models/orqa_model.py", line 24, in <module>
    from language.orqa import ops as orqa_ops
  File "/Users/ya/Documents/realm/language/language/orqa/ops/__init__.py", line 23, in <module>
    os.path.join(os.path.dirname(os.path.abspath(__file__)), "orqa_ops.so"))
  File "/Users/ya/opt/anaconda3/envs/orqa/lib/python3.7/site-packages/tensorflow/python/framework/load_library.py", line 58, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: dlopen(/Users/ya/Documents/realm/language/language/orqa/ops/orqa_ops.so, 6): image not found

```

**Comment by youssefavx** [comment]
I'm running all of this on a Macbook Pro Retina 2013 15" with MacOS Mojave 10.14

**Comment by kentonl** [comment]
I don't think ScaNN supports OSX out of the box, but you can try their instructions to compile it yourself: https://github.com/google-research/google-research/tree/master/scann.

Regarding the missing `orqa_ops`, please read the full README for instructions. There are extra compilations steps you need to do.

**Comment by youssefavx** [comment]
Thank you for the help! Feel free to ignore me at any point if this is too cumbersome haha. 

I tried to build scann from source using:

`python3 configure.py CC=clang-8 bazel build -c opt --copt=-mavx2 --copt=-mfma --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" --cxxopt="-std=c++17" --copt=-fsized-deallocation --copt=-w :build_pip_pkg ./bazel-bin/build_pip_pkg`

And got this error:
```
  File "configure.py", line 6
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
```

Configure.py seems to be all html and not python? 

I tried applying the compilations for orqa and the error did go away but was met with a new error which from the looks of it is due to missing scann.

I ran this again:

`python3 -m language.orqa.predict.orqa_demo \ --model_dir=gs://realm-data/orqa_nq_model_from_realm \ --port=8080
`

And got this error:

```
WARNING:tensorflow:scann is not available.
WARNING:tensorflow:From /Users/josephvanrowe/opt/anaconda3/envs/orqa/lib/python3.7/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
Traceback (most recent call last):
  File "/Users/josephvanrowe/opt/anaconda3/envs/orqa/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/josephvanrowe/opt/anaconda3/envs/orqa/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/josephvanrowe/Documents/realm/language/language/orqa/predict/orqa_demo.py", line 105, in <module>
    tf.app.run()
  File "/Users/josephvanrowe/opt/anaconda3/envs/orqa/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/Users/josephvanrowe/opt/anaconda3/envs/orqa/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/Users/josephvanrowe/opt/anaconda3/envs/orqa/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/Users/josephvanrowe/Documents/realm/language/language/orqa/predict/orqa_demo.py", line 83, in main
    predictor = orqa_model.get_predictor(FLAGS.model_dir)
  File "/Users/josephvanrowe/Documents/realm/language/language/orqa/models/orqa_model.py", line 504, in get_predictor
    with tf.io.gfile.GFile(os.path.join(model_dir, "params.json")) as f:
  File "/Users/josephvanrowe/opt/anaconda3/envs/orqa/lib/python3.7/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
