### ISSUE TITLE
ORQA/REALM - Invalid argument: indices[0] = 10311577 is not in

### ISSUE THREAD

**Issue by ioannist** [google-research/language#89]
I am trying to run Orqa finetuning with Realm models on my own data set. I have created the blocks.tfr file and used --num_block_records=154800 which is the number of rows in my records file. 

I launch fine-tuning with

python -m language.orqa.experiments.orqa_experiment --retriever_module_path=$(pwd)/language/orqa/gs/realm-data/cc_news_pretrained/embedder --reader_module_path=$(pwd)/language/orqa/gs/realm-data/cc_news_pretrained/bert --block_records_path=$(pwd)/language/orqa/gs/orqa-data/trump-blocks/blocks.tfr --num_block_records=154800 --data_root=$(pwd)/language/orqa/gs/orqa-data/resplit --model_dir=$(pwd)/language/orqa/models/orqa_trump_model_from_realm --dataset_name=TrumpQuestions --num_train_steps=$(( 3417 * 20 )) --save_checkpoints_steps=1000

Everything seems to go well in the first ten minutes, but then I get this error
Invalid argument: indices[0] = 10311577 is not in [0, 154800)

I am not sure where 10311577 is coming from. Any ideas?

```
2020-10-13 13:06:30.130961: I tensorflow/core/kernels/data/shuffle_dataset_op.cc                        :199] Shuffle buffer filled.
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/orqa/lib/python3.7/site-packages/tensorflow_                        core/python/client/session.py", line 1367, in _do_call
    return fn(*args)
  File "/home/ubuntu/anaconda3/envs/orqa/lib/python3.7/site-packages/tensorflow_                        core/python/client/session.py", line 1352, in _run_fn
    target_list, run_metadata)
  File "/home/ubuntu/anaconda3/envs/orqa/lib/python3.7/site-packages/tensorflow_                        core/python/client/session.py", line 1445, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) fo                        und.
  (0) Invalid argument: indices[0] = 10311577 is not in [0, 154800)
         [[{{node GatherV2_2}}]]
  (1) Invalid argument: indices[0] = 10311577 is not in [0, 154800)
         [[{{node GatherV2_2}}]]
         [[reader/RaggedRange_4/_8285]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/orqa/lib/python3.7/runpy.py", line 193, in _                        run_module_as_main
    "__main__", mod_spec)
  File "/home/ubuntu/anaconda3/envs/orqa/lib/python3.7/runpy.py", line 85, in _r                        un_code
    exec(code, run_globals)
  File "/home/ubuntu/ioannis/language/language/orqa/experiments/orqa_experiment.                        py", line 84, in <module>
    app.run(main)
  File "/home/ubuntu/anaconda3/envs/orqa/lib/python3.7/site-packages/absl/app.py                        ", line 300, in run
    _run_main(main, args)
  File "/home/ubuntu/anaconda3/envs/orqa/lib/python3.7/site-packages/absl/app.py                        ", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/ubuntu/ioannis/language/language/orqa/experiments/orqa_experiment.                        py", line 79, in main
    params_fname="params.json")
  File "/home/ubuntu/ioannis/language/language/common/utils/experiment_utils.py"                        , line 169, in run_experiment
    eval_spec=eval_spec)
  File "/home/ubuntu/anaconda3/envs/orqa/lib/python3.7/site-packages/tensorflow_                        estimator/python/estimator/training.py", line 473, in train_and_evaluate
    return executor.run()
  File "/home/ubuntu/anaconda3/envs/orqa/lib/python3.7/site-packages/tensorflow_                        estimator/python/estimator/training.py", line 613, in run
    return self.run_local()
  File "/home/ubuntu/anaconda3/envs/orqa/lib/python3.7/site-packages/tensorflow_                        estimator/python/estimator/training.py", line 714, in run_local
    saving_listeners=saving_listeners)
  File "/home/ubuntu/anaconda3/envs/orqa/lib/python3.7/site-packages/tensorflow_                        estimator/python/estimator/estimator.py", line 374, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/ubuntu/anaconda3/envs/orqa/lib/python3.7/site-packages/tensorflow_                        estimator/python/estimator/estimator.py", line 1164, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/home/ubuntu/anaconda3/envs/orqa/lib/python3.7/site-packages/tensorflow_                        estimator/python/estimator/estimator.py", line 1198, in _train_model_default
    saving_listeners)
  File "/home/ubuntu/anaconda3/envs/orqa/lib/python3.7/site-packages/tensorflow_                        estimator/python/estimator/estimator.py", line 1497, in _train_with_estimator_sp                        ec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/home/ubuntu/anaconda3/envs/orqa/lib/python3.7/site-packages/tensorflow_                        core/python/training/monitored_session.py", line 778, in run
    run_metadata=run_metadata)
  File "/home/ubuntu/anaconda3/envs/orqa/lib/python3.7/site-packages/tensorflow_                        core/python/training/monitored_session.py", line 1283, in run
    run_metadata=run_metadata)
  File "/home/ubuntu/anaconda3/envs/orqa/lib/python3.7/site-packages/tensorflow_                        core/python/training/monitored_session.py", line 1384, in run
    raise six.reraise(*original_exc_info)
  File "/home/ubuntu/anaconda3/envs/orqa/lib/python3.7/site-packages/six.py", li                        ne 703, in reraise
    raise value
  File "/home/ubuntu/anaconda3/envs/orqa/lib/python3.7/site-packages/tensorflow_                        core/python/training/monitored_session.py", line 1369, in run
    return self._sess.run(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/orqa/lib/python3.7/site-packages/tensorflow_                        core/python/training/monitored_session.py", line 1442, in run
    run_metadata=run_metadata)
  File "/home/ubuntu/anaconda3/envs/orqa/lib/python3.7/site-packages/tensorflow_                        core/python/training/monitored_session.py", line 1200, in run
    return self._sess.run(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/orqa/lib/python3.7/site-packages/tensorflow_                        core/python/client/session.py", line 960, in run
    run_metadata_ptr)
  File "/home/ubuntu/anaconda3/envs/orqa/lib/python3.7/site-packages/tensorflow_                        core/python/client/session.py", line 1183, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/ubuntu/anaconda3/envs/orqa/lib/python3.7/site-packages/tensorflow_                        core/python/client/session.py", line 1361, in _do_run
    run_metadata)
  File "/home/ubuntu/anaconda3/envs/orqa/lib/python3.7/site-packages/tensorflow_                        core/python/client/session.py", line 1386, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) fo                        und.
  (0) Invalid argument: indices[0] = 10311577 is not in [0, 154800)
         [[node GatherV2_2 (defined at /ioannis/language/language/orqa/models/or                        qa_model.py:148) ]]
  (1) Invalid argument: indices[0] = 10311577 is not in [0, 154800)
         [[node GatherV2_2 (defined at /ioannis/language/language/orqa/models/or                        qa_model.py:148) ]]
         [[reader/RaggedRange_4/_8285]]
0 successful operations.
0 derived errors ignored.

Errors may have originated from an input operation.
Input Source operations connected to node GatherV2_2:
 blocks/read (defined at /ioannis/language/language/orqa/models/orqa_model.py:14                        7)
 Squeeze (defined at /ioannis/language/language/orqa/models/orqa_model.py:129)

Input Source operations connected to node GatherV2_2:
 blocks/read (defined at /ioannis/language/language/orqa/models/orqa_model.py:14                        7)
 Squeeze (defined at /ioannis/language/language/orqa/models/orqa_model.py:129)

Original stack trace for 'GatherV2_2':
  File "/anaconda3/envs/orqa/lib/python3.7/runpy.py", line 193, in _run_module_a                        s_main
    "__main__", mod_spec)
  File "/anaconda3/envs/orqa/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/ioannis/language/language/orqa/experiments/orqa_experiment.py", line 84                        , in <module>
    app.run(main)
  File "/anaconda3/envs/orqa/lib/python3.7/site-packages/absl/app.py", line 300,                         in run
    _run_main(main, args)
  File "/anaconda3/envs/orqa/lib/python3.7/site-packages/absl/app.py", line 251,                         in _run_main
    sys.exit(main(argv))
  File "/ioannis/language/language/orqa/experiments/orqa_experiment.py", line 79                        , in main
    params_fname="params.json")
  File "/ioannis/language/language/common/utils/experiment_utils.py", line 169,                         in run_experiment
    eval_spec=eval_spec)
  File "/anaconda3/envs/orqa/lib/python3.7/site-packages/tensorflow_estimator/py                        thon/estimator/training.py", line 473, in train_and_evaluate
    return executor.run()
  File "/anaconda3/envs/orqa/lib/python3.7/site-packages/tensorflow_estimator/py                        thon/estimator/training.py", line 613, in run
    return self.run_local()
  File "/anaconda3/envs/orqa/lib/python3.7/site-packages/tensorflow_estimator/py                        thon/estimator/training.py", line 714, in run_local
    saving_listeners=saving_listeners)
  File "/anaconda3/envs/orqa/lib/python3.7/site-packages/tensorflow_estimator/py                        thon/estimator/estimator.py", line 374, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/anaconda3/envs/orqa/lib/python3.7/site-packages/tensorflow_estimator/py                        thon/estimator/estimator.py", line 1164, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/anaconda3/envs/orqa/lib/python3.7/site-packages/tensorflow_estimator/py                        thon/estimator/estimator.py", line 1194, in _train_model_default
    features, labels, ModeKeys.TRAIN, self.config)
  File "/anaconda3/envs/orqa/lib/python3.7/site-packages/tensorflow_estimator/py                        thon/estimator/estimator.py", line 1152, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/ioannis/language/language/orqa/models/orqa_model.py", line 413, in mode                        l_fn
    params=params)
  File "/ioannis/language/language/orqa/models/orqa_model.py", line 148, in retr                        ieve
    retrieved_blocks = tf.gather(blocks, retrieved_block_ids)
  File "/anaconda3/envs/orqa/lib/python3.7/site-packages/tensorflow_core/python/                        util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/anaconda3/envs/orqa/lib/python3.7/site-packages/tensorflow_core/python/                        ops/array_ops.py", line 4108, in gather
    return gen_array_ops.gather_v2(params, indices, axis, name=name)
  File "/anaconda3/envs/orqa/lib/python3.7/site-packages/tensorflow_core/python/                        ops/gen_array_ops.py", line 3690, in gather_v2
    batch_dims=batch_dims, name=name)
  File "/anaconda3/envs/orqa/lib/python3.7/site-packages/tensorflow_core/python/                        framework/op_def_library.py", line 742, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "/anaconda3/envs/orqa/lib/python3.7/site-packages/tensorflow_core/python/                        framework/ops.py", line 3322, in _create_op_internal
    op_def=op_def)
  File "/anaconda3/envs/orqa/lib/python3.7/site-packages/tensorflow_core/python/                        framework/ops.py", line 1756, in __init__
    self._traceback = tf_stack.extract_stack()
```

**Comment by mchari** [comment]
@ioannist , were you able to resolve this issue. 
how did you create the tfr file ? i am starting to look into this and wondered if there was any quick reference that would help me get going.
thanks!

**Comment by ioannist** [comment]
@michari no, unfortunately not :(

**Comment by mchari** [comment]
@ioannist , any guidance on how to create a working tfr file ?

**Comment by ioannist** [comment]
can't recall exactly but I think I created a raw text file in the same format as the Wikipedia raw text file, and then I ran language.preprocessing.preprocess_wiki_extractor

**Comment by johnbager** [comment]
@ioannist ,hello,i’m sorry to bother you.  Could you share me about how do you deal one doc to tfr。（what about language.preprocessing.preprocess_wiki_extractor)

**Comment by Kamel773** [comment]
@ioannist I have the same issues. Have you solved it?

**Comment by Kamel773** [comment]
cc @kentonl  
I am working on fine tuning ORQA in my own dataset, and I have the same issues. We appreciate your help in solving this issues. 

Kind regards,

**Comment by gnan-cyber** [comment]
@ioannist @Kamel773 @mchari @johnbager @dhgarrette Tunner Celebration at October 31 at 19:10

# Wear a hat, fun, dance and enjoy!

The famous Sprunki mascot is...

Tunner!

**Comment by johnbager** [comment]
收到

**Comment by gnan-cyber** [comment]
@johnbager Tunner has a style: hair, hat, coat

**Comment by gnan-cyber** [comment]
<img width="400" height="400" alt="Image" src="https://github.com/user-attachments/assets/b6afd575-23f9-4162-bb57-197bb2b0f8a6" />

<img width="400" height="400" alt="Image" src="https://github.com/user-attachments/assets/7fba5cdb-91e0-4bf5-b0a7-663b1e4b34bf" />

<img width="400" height="400" alt="Image" src="https://github.com/user-attachments/assets/f39345b4-352d-419a-8501-6271e6b9790c" />

<img width="400" height="400" alt="Image" src="https://github.com/user-attachments/assets/5385aa1c-b3a8-4264-8c5b-cf3e529f1741" />

<img width="400" height="400" alt="Image" src="https://github.com/user-attachments/assets/268670ca-f639-4b46-8c85-513ed39d372a" />

<img width="400" height="400" alt="Image" src="https://github.com/user-attachments/assets/9f714509-b886-4b17-8f0f-e2e7bd04afc0" />

<img width="400" height="400" alt="Image" src="https://github.com/user-attachments/assets/4a7ddc5e-2d2a-44c7-8bb2-70259ff0f20a" />

<img width="400" height="400" alt="Image" src="https://github.com/user-attachments/assets/5ff966e2-a0a1-4cf7-ad03-4f76c8612e46" />

<img width="400" height="400" alt="Image" src="https://github.com/user-attachments/assets/0d175ea6-61c5-4766-be46-82e5cd93d0b8" />

<img width="400" height="400" alt="Image" src="https://github.com/user-attachments/assets/d2dda6ea-a690-4e34-acf5-9c5c2d16b93d" />

<img width="400" height="400" alt="Image" src="https://github.com/user-attachments/assets/f5b4e492-16ca-40bd-b7c0-e7d6a986a70f" />

<img width="400" height="400" alt="Image" src="https://github.com/user-attachments/assets/3ebddf46-5402-4274-923d-f9e438562141" />

<img width="400" height="400" alt="Image" src="https://github.com/user-attachments/assets/e6f1f784-e89b-484c-a648-b3d3bb18c2f0" />

<img width="400" height="400" alt="Image" src="https://github.com/user-attachments/assets/024aeb73-0ebc-43b4-b0bc-6cbdb22e4bac" />

<img width="400" height="400" alt="Image" src="https://github.com/user-attachments/assets/4b67a6be-9993-44e8-93b0-685449e5299a" />

<img width="400" height="400" alt="Image" src="https://github.com/user-attachments/assets/ac27cab2-d766-4034-9022-95f705f4cf62" />

<img width="400" height="400" alt="Image" src="https://github.com/user-attachments/assets/b2046d85-feaf-4086-a331-2f297273db0f" />

<img width="400" height="400" alt="Image" src="https://github.com/user-attachments/assets/8b90b2ef-cbd4-46af-8126-f2c7004f38b7" />

<img width="400" height="400" alt="Image" src="https://github.com/user-attachments/assets/400c5bac-caf8-4245-a6f6-0ddee5c7a6ef" />

<img width="400" height="400" alt="Image" src="https://github.com/user-attachments/assets/4d4bd173-f4cf-4041-a25a-432a7459a550" />

<img width="400" height="400" alt="Image" src="https://github.com/user-attachments/assets/524b42a8-1107-4b5f-8b5a-2e8e2e71d827" />

<img width="400" height="400" alt="Image" src="https://github.com/user-attachments/assets/00cb594f-4d9e-4b5f-997f-edf091619094" />

@johnbager and @southamericamemes181

**Comment by southamericamemes181** [comment]
<img width="400" height="400" alt="Image" src="https://github.com/user-attachments/assets/64182ceb-68d1-49f8-834e-696b33fa6d89" />

<img width="400" height="400" alt="Image" src="https://github.com/user-attachments/assets/76000d18-9ea6-4af1-a093-62400e19314f" />

<img width="400" height="400" alt="Image" src="https://github.com/user-attachments/assets/671ffdfa-3e0d-418d-a309-e30133cb9454" />

<img width="400" height="400" alt="Image" src="https://github.com/user-attachments/assets/0fe42dab-571b-479e-9136-9d24471d2ca5" />

<img width="400" height="400" alt="Image" src="https://github.com/user-attachments/assets/74d9988b-12ca-4162-b57d-e674e80908f1" />

<img width="400" height="400" alt="Image" src="https://github.com/user-attachments/assets/e694a208-c017-47c4-81d6-1f60ef07ea2e" />

**Comment by gnan-cyber** [comment]
Yeah!

**Comment by southamericamemes181** [comment]
Let's go!

**Comment by gnan-cyber** [comment]
YAYAYAYAY
