### ISSUE TITLE
Undefined symbol error in ORQA; preprocess_wiki_extractor.py

### ISSUE THREAD

**Issue by priyamtejaswin** [google-research/language#99]
Hi,

I'm trying to create TFR Blocks on my custom dataset using the `language.orqa.preprocessing.preprocess_wiki_extractor` module.

Running the command in the README throws the following error:
```bash
$ CUDA_VISIBLE_DEVICES=0,3 python -m language.orqa.preprocessing.preprocess_wiki_extractor --input_pattern=../splittext/part_* --output_pattern=../preprocess-wiki-extractor
Traceback (most recent call last):
  File "/projects/anaconda3/envs/condaorqa/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/projects/anaconda3/envs/condaorqa/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/projects/language/language/orqa/preprocessing/preprocess_wiki_extractor.py", line 39, in <module>
    from language.orqa.utils import bert_utils
  File "/projects/language/language/orqa/utils/bert_utils.py", line 20, in <module>
    import tensorflow_text as tf_text
  File "/projects/anaconda3/envs/condaorqa/lib/python3.7/site-packages/tensorflow_text/__init__.py", line 21, in <module>
    from tensorflow_text.python import metrics
  File "/projects/anaconda3/envs/condaorqa/lib/python3.7/site-packages/tensorflow_text/python/metrics/__init__.py", line 20, in <module>
    from tensorflow_text.python.metrics.text_similarity_metric_ops import *
  File "/projects/anaconda3/envs/condaorqa/lib/python3.7/site-packages/tensorflow_text/python/metrics/text_similarity_metric_ops.py", line 28, in <module>
    gen_text_similarity_metric_ops = load_library.load_op_library(resource_loader.get_path_to_datafile('_text_similarity_metric_ops.so'))
  File "/projects/anaconda3/envs/condaorqa/lib/python3.7/site-packages/tensorflow_core/python/framework/load_library.py", line 57, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /projects/anaconda3/envs/condaorqa/lib/python3.7/site-packages/tensorflow_text/python/metrics/_text_similarity_metric_ops.so: undefined symbol: _ZN10tensorflow12OpDefBuilder4AttrESs
```

I did find a Github issue under `tensorflow-text` https://github.com/tensorflow/text/issues/192
The solution (as suggested by a user) is to update to `tensorflow-text==2.2.0`
However, this upgrades `tensorflow` to `2.2.0` as well.

**The ORQA codebase requires `2.1.0`** -- any thoughts would be helpful.

Thanks for releasing the codebase!

**Comment by priyamtejaswin** [comment]
Nevermind. 
Creating a new environment with the `requirements.txt` file solved the problem.
I'm guessing this was some version issue ...
